CREATE TABLE password_reset_tokens (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

   token VARCHAR(255) NOT NULL UNIQUE,

   user_id BIGINT NOT NULL,

   created_at TIMESTAMP NOT NULL,

   expires_at TIMESTAMP NOT NULL,

   used_at TIMESTAMP NULL,

   CONSTRAINT fk_password_reset_user
       FOREIGN KEY (user_id)
           REFERENCES users(id)
);