CREATE TABLE projects (
  id BIGSERIAL PRIMARY KEY,

  name VARCHAR(150) NOT NULL,

  description VARCHAR(500),

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);